### ISSUE TITLE
Virtual Interapp MIDI

### ISSUE THREAD

**Issue by owlandfox** [ArthurVasseur/USB-Midi-Android-Plugin#8]
Currently building an app in Unity for Oculus Quest and require virtual MIDI connection. In our scene we have a world space canvas webview that presents webpages with webmidi functionality. We wish to communicate with this webview via midi from 3D UI in Unity scene. Is this possible?

**Comment by ArthurVasseur** [comment]
Hello

The USB-Midi-Android-Plugin is not capable of creating a virtual device; it only forwards MIDI events from the USB to the C# functions.

**Comment by owlandfox** [comment]
OK Thanks for the reply.
